


####
integration:
  host: "https://rgr3viiqdl8sikgv.public.blob.vercel-storage.com/"
  produtos:
     url: "produtos-mnboX5IPl6VgG390FECTKqHsD9SkLS.json"
  clientes:
     url: "clientes-Vz1U6aR3GTsjb3W8BRJhcNKmA81pVh.json"
